/**
 * Signed-URL middleware for the Local storage driver.
 *
 * Verifies the HMAC produced by {@link LocalDriver.getSignedUrl} and,
 * on success, serves the file from the driver. Tampered signatures →
 * 403 `E_INVALID_SIGNATURE`. Expired `exp` → 403 `E_EXPIRED_SIGNATURE`.
 * Missing query params → falls through to `next()` so unsigned routes
 * can coexist on the same prefix.
 *
 * @implements Story 43.2 AC 5
 */

import { createHmac, timingSafeEqual } from "node:crypto";
import * as path from "node:path";
import { inferMimeType } from "./mime-types.js";
import type { LocalDriver, StorageManager } from "./StorageManager.js";

/**
 * Minimal request/response contract the signed-route handler needs.
 * Matches Ream's `HttpContext` structurally — the Ream HttpContext
 * naturally satisfies it via structural subtyping — but avoids
 * importing the concrete Ream type, which keeps the coupling light
 * and lets tests build plain-object mocks without double-casts.
 */
export interface SignedRouteResponse {
	status(code: number): SignedRouteResponse;
	header(name: string, value: string): SignedRouteResponse;
	sendBuffer(buf: Buffer): void;
	json(data: unknown): void;
}

export interface SignedRouteHttpContext {
	request: {
		method(): string;
		path(): string;
		/**
		 * Parsed query string as an object — matches Ream's real
		 * `Request.qs()` contract (which returns
		 * `Record<string, unknown>`). The middleware pulls `exp` and
		 * `sig` by key; this is why the earlier string-returning
		 * variant silently bypassed verification in production.
		 */
		qs?(): Record<string, unknown>;
		header(name: string): string | undefined;
	};
	response: SignedRouteResponse;
}

export interface SignedRouteOptions {
	storage: StorageManager;
	/**
	 * The LocalDriver instance that produced the signatures. The
	 * middleware reads its HMAC secret via `getSigningSecret()` to
	 * recompute the expected signature.
	 */
	driver: LocalDriver;
	/** URL prefix for signed file serving (default: `/storage`). Must
	 *  match the prefix used by `LocalDriver.url()`. */
	prefix?: string;
}

type SignedRouteMiddleware = (
	ctx: SignedRouteHttpContext,
	next: () => Promise<void>,
) => Promise<void>;

/**
 * Build an async Ream middleware that verifies HMAC-signed URLs
 * generated by `LocalDriver.getSignedUrl`.
 */
export function createSignedRouteHandler(
	options: SignedRouteOptions,
): SignedRouteMiddleware {
	const prefix = options.prefix ?? "/storage";
	if (prefix === "") {
		throw new Error(
			"createSignedRouteHandler: prefix cannot be empty. Use '/storage' (default) or a specific path.",
		);
	}
	const secret = options.driver.getSigningSecret();
	if (secret === null) {
		throw new Error(
			"createSignedRouteHandler: driver has no signingSecret configured. Pass { signingSecret } to LocalDriver first.",
		);
	}
	const storage = options.storage;

	return async (ctx, next) => {
		if (ctx.request.method() !== "GET" && ctx.request.method() !== "HEAD") {
			return next();
		}

		const reqPath = ctx.request.path();
		if (!reqPath.startsWith(prefix)) return next();
		const after = reqPath[prefix.length];
		if (after !== undefined && after !== "/") return next();

		// Extract filePath from the URL — URL-DECODED so it matches
		// what the signer used. `LocalDriver.getSignedUrl` encodes each
		// path segment; we decode here before recomputing the HMAC.
		const encodedPath = reqPath.slice(prefix.length).replace(/^\//, "");
		if (encodedPath === "") return next();
		let filePath: string;
		try {
			filePath = decodeSegments(encodedPath);
		} catch {
			ctx.response.status(403).json({
				error: { code: "E_INVALID_SIGNATURE", message: "Malformed path" },
			});
			return;
		}

		// Pull `exp`/`sig` from the parsed query object — matches
		// Ream's `Request.qs()` contract (`Record<string, unknown>`).
		const qs = readQueryObject(ctx);
		const expRaw = readStringParam(qs, "exp");
		const sigHex = readStringParam(qs, "sig");
		if (expRaw === null || sigHex === null) {
			// No signature present — hand off to the next middleware so
			// unsigned routes (e.g. StaticMiddleware) can handle it.
			return next();
		}

		// Validate sig shape up-front: 64 hex chars (sha256). Rejects
		// truncated/garbage sigs with a distinct code before we hit the
		// HMAC path. `Buffer.from(x, 'hex')` silently truncates invalid
		// input, so relying on length-after-decode is the wrong guard.
		if (!/^[a-f0-9]{64}$/.test(sigHex)) {
			ctx.response.status(403).json({
				error: {
					code: "E_INVALID_SIGNATURE",
					message: "Malformed signature",
				},
			});
			return;
		}

		// Strict canonical decimal: parseInt accepts trailing garbage,
		// signs, leading whitespace, etc., which would let multiple
		// `expRaw` query-strings collide on the same valid signature.
		const exp = Number.parseInt(expRaw, 10);
		if (!/^\d+$/.test(expRaw) || !Number.isFinite(exp)) {
			ctx.response.status(403).json({
				error: { code: "E_INVALID_SIGNATURE", message: "Malformed expiry" },
			});
			return;
		}

		// Constant-time HMAC verification on the decoded path. The regex
		// check above already guarantees 32 bytes, so `timingSafeEqual`
		// cannot throw on a length mismatch here. Run BEFORE the expiry
		// check so the response time cannot leak whether a sig was valid
		// for an expired URL versus invalid for a fresh one.
		const expected = createHmac("sha256", secret)
			.update(`${filePath}\n${exp}`)
			.digest();
		const provided = Buffer.from(sigHex, "hex");
		if (!timingSafeEqual(provided, expected)) {
			ctx.response.status(403).json({
				error: { code: "E_INVALID_SIGNATURE", message: "Invalid signature" },
			});
			return;
		}

		if (exp * 1000 <= Date.now()) {
			ctx.response.status(403).json({
				error: { code: "E_EXPIRED_SIGNATURE", message: "Signed URL expired" },
			});
			return;
		}

		// Signature verified — serve the file.
		const content = await storage.get(filePath);
		if (content === null) {
			ctx.response
				.status(404)
				.json({ error: { code: "E_NOT_FOUND", message: "File not found" } });
			return;
		}
		const ext = path.extname(filePath).toLowerCase();
		ctx.response.header("Content-Type", inferMimeType(ext));
		ctx.response.header("Content-Length", String(content.length));
		if (ctx.request.method() === "HEAD") {
			ctx.response.status(200);
			return;
		}
		ctx.response.status(200).sendBuffer(content);
	};
}

/**
 * Read the parsed query object from the HttpContext. Matches Ream's
 * `Request.qs()` contract (object). Returns an empty object when the
 * adapter does not expose `qs()` — in that rare case every request
 * will fall through to `next()`, which is the safe behaviour.
 */
function readQueryObject(ctx: SignedRouteHttpContext): Record<string, unknown> {
	if (typeof ctx.request.qs === "function") {
		return ctx.request.qs();
	}
	return {};
}

/** Read a query param as string, or return `null` if absent / non-string. */
function readStringParam(
	qs: Record<string, unknown>,
	key: string,
): string | null {
	const raw = qs[key];
	return typeof raw === "string" ? raw : null;
}

/**
 * Decode each URL-encoded path segment. Throws if any segment
 * contains invalid percent-escapes (`decodeURIComponent` throws on
 * malformed input).
 */
function decodeSegments(encodedPath: string): string {
	return encodedPath
		.split("/")
		.map((seg) => decodeURIComponent(seg))
		.join("/");
}
